### ISSUE TITLE
暴露metrics，接入prometheus

### ISSUE THREAD

**Issue by kybt** [ygqygq2/nacos-helm#21]
需要接入prometheus监控，修改values.yaml，暴露metrics
metrics:
    enabled: true
    serviceMonitor:
        enabled: true

部署后，查看/nacos/v1/ns/operator/metrics接口只有status指标，没有其他的监控指标，
请帮我看看是缺少什么参数吗？

**Comment by ygqygq2** [comment]
你先看看官方文档，然后不使用镜像方式。我也不清楚他们的镜像有没有暴露相关接口

**Comment by kybt** [comment]
我试了nacos 2.0.4版本的，没问题，   应该是从2.1.0之后的版本都禁用了

**Comment by ygqygq2** [comment]
> 我试了nacos 2.0.4版本的，没问题， 应该是从2.1.0之后的版本都禁用了

那就看看能不能使用 configmap 方式打开配置，不然你只能自己做个镜像了。
