### ISSUE TITLE
Failed to install nacos-helm for mysql 8.0

### ISSUE THREAD

**Issue by yepei14** [ygqygq2/nacos-helm#27]
When configuring nacos to connect to external mysql with version 8.0, nacos-init-db failed with following error:

![image](https://github.com/ygqygq2/nacos-helm/assets/11693957/09a319c3-8577-46d6-87e4-e80b7eebf5a2)

The ygqygq2/mysql-exec-sql:latest uses mysql 5.7 client and cannot connect to mysql 8.0.

Need to upgrade ygqygq2/mysql-exec-sql to support mysql 8.0 server.

**Comment by ygqygq2** [comment]
Thanks, I'll upgrade it.

**Comment by ygqygq2** [comment]
Fixed. https://github.com/ygqygq2/docker-autodevops/issues/44
