### ISSUE TITLE
helm拉取执行nacos失败

### ISSUE THREAD

**Issue by Charliebinbin** [ygqygq2/nacos-helm#7]
你好，请问下我在我的K8S集群使用helm拉取您在https://artifacthub.io/packages/helm/ygqygq2/nacos上的nacos最新chart仓库，执行

 ~]# helm install my-nacos ygqygq2/nacos --version 2.0.1

时，系统报错：

Error: found in Chart.yaml, but missing in charts/ directory: common, mysql

请问下是什么原因？如何快速通过helm启动执行您的nacos chart资源？

**Comment by zhangfugui727** [comment]
同样，我看其他案例说需要更新依赖，但是我mysql那里设置的false，使用的外部数据库

**Comment by Charliebinbin** [comment]
> 

你好，那请问你通过helm启动nacos是成功了吗？

**Comment by Charliebinbin** [comment]
> 同样，我看其他案例说需要更新依赖，但是我mysql那里设置的false，使用的外部数据库
